[package]
name = "mentci-box"
version = "0.1.0"
edition = "2021"
description = "Bootstrap and reliable sandbox executable for Mentci-AI."

[dependencies]
anyhow = "1.0"
mentci-box-lib = { path = "../mentci-box-lib" }
tracing = "0.1"
tracing-subscriber = "0.3"
